"""add purchase history checkin support

Revision ID: 9da9adc518dc
Revises: 301a44efdd4f
Create Date: 2026-08-01 14:41:47.706985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da9adc518dc'
down_revision: Union[str, None] = '301a44efdd4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_history', sa.Column('checkin_sent', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_history', 'checkin_sent')
    # ### end Alembic commands ###
